version: '2'
services:
  general_db:
    image: postgres:9.5.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - PGPASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"

  go-api:
    build: "."
    container_name: "mozart-config-api"
    environment:
      - APP_ENV=dev
      - PGPASSWORD=postgres
    expose:
      - "8080"
    links:
      - "general_db:db"
    ports:
      - "6001:8080"
    restart: "always"
