version: '2'
services:
  general_db:
    image: postgres:9.5.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - PGPASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"

  general_db-migrate:
    image: davey/migrate-ready
    entrypoint: "bash -c \"bash <(tr -d '\r' < /migrations/docker_db.sh)\""
    environment:
      - PGPASSWORD=postgres
    volumes:
      - ./infrastructure/:/migrations
    links:
      - "general_db:db"
    depends_on:
      - "general_db"
